'use client';

import { FormEvent, useState } from 'react';
import { ArrowLeft, CalendarDays, ClipboardList, HeartPulse, LockKeyhole, LogIn } from 'lucide-react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';

type Dashboard = { doctor: { full_name: string; specialty: string }; appointments: Array<{ id: string; patient_name: string; appointment_date: string; appointment_time: string; appointment_number: string; status: string }>; records: Array<{ id: string; patient_name: string; record_type: string; summary: string }> };

export default function DoctorsPortalPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function signIn(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const supabase = getSupabaseBrowser(); const { data, error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError || !data.session) throw new Error(signInError?.message || 'Unable to sign in.'); const response = await fetch('/api/doctors/dashboard', { headers: { Authorization: `Bearer ${data.session.access_token}` } }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to load your doctor workspace.'); setDashboard(result); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.'); } finally { setLoading(false); } }
  if (!dashboard) return <main className="grid min-h-screen place-items-center bg-[#f7fbff] px-5 text-[#082b6f]"><div className="w-full max-w-md"><a href="/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16} /> Back to homepage</a><form onSubmit={signIn} className="mt-7 rounded-3xl bg-white p-7 shadow-[0_18px_50px_rgb(8_43_111/10%)] sm:p-9"><span className="grid h-12 w-12 place-items-center rounded-xl bg-[#f39a1e] text-white"><HeartPulse size={24} /></span><p className="mt-7 text-xs font-bold uppercase tracking-[0.16em] text-[#f39a1e]">Doctor portal</p><h1 className="mt-2 text-3xl font-extrabold">Sign in to your account</h1><p className="mt-3 text-sm leading-6 text-[#667aa0]">Access your upcoming patients and medical records.</p><div className="mt-7 grid gap-4"><label className="grid gap-2 text-sm font-bold">Email address<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" required className="rounded-xl border border-[#d5e1f1] px-4 py-3 font-normal outline-none focus:border-[#f39a1e]" /></label><label className="grid gap-2 text-sm font-bold">Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" required className="rounded-xl border border-[#d5e1f1] px-4 py-3 font-normal outline-none focus:border-[#f39a1e]" /></label></div>{error && <p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-[#f39a1e] px-5 py-3.5 text-sm font-bold text-white disabled:opacity-60">{loading ? 'Signing in…' : 'Sign in'} <LogIn size={16} /></button><p className="mt-5 flex items-center justify-center gap-2 text-xs text-[#8698b2]"><LockKeyhole size={14} /> Protected doctor access</p></form></div></main>;
  return <main className="min-h-screen bg-[#f7fbff] px-5 py-8 text-[#082b6f]"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between"><a href="/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={16} /> Homepage</a><button onClick={async () => { await getSupabaseBrowser().auth.signOut(); setDashboard(null); }} className="text-sm font-bold text-[#667aa0]">Sign out</button></div><div className="mt-7 rounded-3xl bg-[#082b6f] p-7 text-white sm:p-9"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f8be66]">Doctor workspace</p><h1 className="mt-2 text-3xl font-extrabold">Welcome, {dashboard.doctor.full_name}.</h1><p className="mt-2 text-sm text-[#c8d5ea]">{dashboard.doctor.specialty}</p></div><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-2xl bg-white p-6 shadow-[0_10px_30px_rgb(8_43_111/7%)]"><div className="flex items-center gap-3"><CalendarDays className="text-[#f39a1e]" /><h2 className="text-xl font-extrabold">Upcoming patients</h2></div>{dashboard.appointments.length ? <div className="mt-5 grid gap-3">{dashboard.appointments.map((appointment) => <article key={appointment.id} className="rounded-xl border border-[#d5e1f1] p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-extrabold">{appointment.patient_name}</h3><p className="mt-1 text-xs text-[#667aa0]">{appointment.appointment_date} · {appointment.appointment_time}</p></div><span className="rounded-full bg-[#e8f8ee] px-2.5 py-1 text-[10px] font-bold text-[#159447]">{appointment.status}</span></div><p className="mt-3 text-[11px] text-[#8698b2]">Reference: {appointment.appointment_number}</p></article>)}</div> : <p className="mt-5 rounded-xl bg-[#f7fbff] p-5 text-sm text-[#667aa0]">No upcoming patients assigned yet.</p>}</section><section className="rounded-2xl bg-white p-6 shadow-[0_10px_30px_rgb(8_43_111/7%)]"><div className="flex items-center gap-3"><ClipboardList className="text-[#f39a1e]" /><h2 className="text-xl font-extrabold">Recent records</h2></div>{dashboard.records.length ? <div className="mt-5 grid gap-3">{dashboard.records.map((record) => <article key={record.id} className="rounded-xl border border-[#d5e1f1] p-4"><p className="text-xs font-bold text-[#f39a1e]">{record.record_type}</p><h3 className="mt-1 text-sm font-extrabold">{record.patient_name}</h3><p className="mt-2 text-xs leading-5 text-[#667aa0]">{record.summary}</p></article>)}</div> : <p className="mt-5 rounded-xl bg-[#f7fbff] p-5 text-sm text-[#667aa0]">No medical records available yet.</p>}</section></div></div></main>;
}
