export const specialtyMatches: Record<string, string[]> = {
  'Primary Care & General Medicine': ['Medical Doctor', 'General Medicine', 'Family Medicine', 'Primary Care'],
  'OB-GYN & Women’s Health': ['Obstetrics and Gynecology'],
  'Obstetrics and Gynecology & Women’s Health': ['Obstetrics and Gynecology'],
  'Pediatrics': ['Pediatrics', 'General Pediatrics'],
  'Diabetes & Endocrinology': ['Endocrinology'],
  'Eye & Vision Doctor': ['Ophthalmology'],
  'Heart & Cardiology': ['Cardiology', 'Adult Cardiology'],
  'Skin & Dermatology': ['Dermatology'],
  'Lungs, Chest & Pulmonology': ['Pulmonology'],
  'Stomach, Digestion & Gastroenterology': ['Gastroenterology'],
  'Ears, Nose & Throat': ['Otolaryngology', 'Otorhinolaryngology'],
  'Kidney & Urine': ['Nephrology', 'Urology'],
  'Brain & Nerves': ['Neurology'],
  'Surgery': ["General Surgery","Surgery"],
  'Cancer & Oncology': ["Oncology","Medical Oncology","Surgical Oncology","Cancer Surgery"],
  'Mental Health & Psychiatry': ["Psychiatry","Psychology"],
  'Allergy & Immunology': ["Allergy and Immunology","Allergology","Immunology"],
  'Infectious Diseases': ["Infectious Diseases"],
  'Sleep Medicine': ["Sleep Medicine"],
  'Pain Medicine': ["Pain Medicine"],
  'Sports Medicine & Rehabilitation': ["Sports Medicine","Physical Medicine and Rehabilitation"],
  'Maternal, Fetal & Newborn Care': ["Maternal-Fetal Medicine","Neonatology"],
  'Aesthetic Medicine': ["Aesthetic Medicine"],
  'Blood & Hematology': ["Hematology"],
  'Liver & Hepatology': ["Hepatology","Liver, Pancreas, and Gallbladder Diseases"],
  'Foot, Ankle & Lower Leg': ["Podiatry"],
  'Joints, Muscles & Bones': ["Orthopedics","Orthopedic Surgery","Rheumatology"],
  'Geriatrics': ["Geriatrics"],
  'Proctology': ["Proctology","Colorectal Surgery"],
  'Hearing & Audiology': ["Audiology","Otology"],
  'Hospice & Palliative Care': ["Hospice and Palliative Medicine","Palliative Medicine"],
  'Anesthesiology': ["Anesthesiology"],
  'Imaging & Radiology': ["Radiology","Diagnostic Radiology"],
  'Poisons & Toxicology': ["Toxicology","Medical Toxicology"],
  'Diet & Nutrition': ["Nutrition and Dietetics","Nutrition","Dietetics"],
  'Lifestyle Medicine': ["Lifestyle Medicine"],
  'Dental Care': ["Dentistry"],
  'Alternative Medicine': ["Alternative Medicine","Integrative Medicine"],
  'Veterinary Medicine': ["Veterinary Medicine"],
};
